import markovify
import json
import time


# Generates captions from scraped Tiktok viral captions
# Uses Markov chain model to generate captions
# Found from search results so they are clearly high performing
# TODO - Add a seed for context
# 30% overlap seems to be the lowest it can go. It hangs on 20.
# Average time seems to be ~0.1, 0.2s
class TiktokCaption:

    def __init__(self, caption: str):
        self.caption = caption
        with open("../data/scraped_results.json", "r") as scraped_results:
            self.ds = json(scraped_results)

        return self.generate_caption()

    def generate_caption(self):
        text_model = markovify.NewlineText(self.ds)
        title = text_model.make_sentence(
            max_overlap_ratio=0.3, min_words=11, max_words=23
        )

        return title


data = [
    "𝗟𝗕𝗪𝗞 𝗛𝗲𝗹𝗹𝗰𝗮𝘁 😈 | 🎥 @The Pro Video | #dodge #challenger #hellcat",
    "F82 ☁️📸 #bmw #f82 #supercar #sportcar #cars #edit #fyp #explore",
    "4k Supra 🛐😮‍💨 | #🔥 #edit #jdm #drift #car #swxft #ae #4k #quality",
    "☆ S U B S C R I B E ☆ #CARS #CAREDIT #TRENDING #CARSTIKTOK",
    "90% of people don't know these hidden features of cars!#tiktok #howto #cartok",
    "#cartoon #cars",
    "Summer nights > winter nights #tiktokcars #fypシ #foryoupage",
    "She sounds awesome 😮‍💨👌🏽 #fyp #bonnielocket #cartok #adamcfest",
    "Winter Car ❄️ [amg.doni] #bmw #m3 #winter #car #foryou",
    "#car #bmw #audi #mercedes #mini #golf #subaru #fyp #fy",
    "#fyp #trek #car #foryoupage #cars #drift #on #fypシ",
    "Loud Cars 😮‍💨🥵 #lamborghiniaventador #supercar #caredit #viral #fyp #capcut",
    "#bmw #car #germany #mperformance #4k #m4 #supercar",
    "Reply to @thelurk66 The first electric miata 😎 | #miata #carsoftiktok #cartok",
    "She is so cute in her little car! This is super common here in Amsterdam!",
    "🥵 𝐅𝐨𝐫𝐝 𝐌𝐮𝐬𝐭𝐚𝐧𝐠 | 🎥 - 𝐀𝐞 𝐞𝐝𝐢𝐭 #carsoftiktok #carphonkbr #caredits",
    "Pov: working on a soon to be drift car 💖 #cargirl #cargirltok #driftcar #carbuild",
    "𝐆𝐓𝐑 𝐑𝟑𝟓 🥴🔥| 🎥 - 𝐀𝐞 𝐞𝐝𝐢𝐭𝐬 #lentejas #🥵 #fyp #teamfx⚜️ #gtr #r35 #caredit",
    "GT3 🔥🔥 | #porsche #gt3rs #luxurycars #supercars #luxurylifestyleeee",
    "You and bro😍 #cars #car #dxb #dubai #uae #porsche #porschebros",
    "𝐓𝐡𝐢𝐬 𝐚𝐮𝐝𝐢𝐨🌚🎥:𝐒𝐰𝐢𝐳.𝐩𝐫𝐨𝐝 #porsche #caredit #car #cars #parati #quality #4k",
    "#g350 #g350d #g350damg #g350dprofessional #amg #amggclass",
    "Driving a manual transmission car is a pleasure, come and learn #gaming",
    "Wait for it. #carexpert",
    "🖤 #gt3 #cartok #cars #porsche #viral #fyp",
    "Underrated Ahh Car 🚗 || @458.media™ @mansory.media @Cars of Somerset™ ||",
    "#hellcat #srt #fypシ",
    "This UFO Car is CRAZY 👽😮‍💨 #supercar #car #ufo #alien #losangeles #la #usa",
    "SPIDER-MAN & HULK SAVING BABY RC CAR! VENOM LIFT BABY RC CAR! 🕷️ 🧟",
    "Will costs 50k or something 🥲 #bugatti #chiron #bugattichiron #carcrash #car",
    "new car video #car #amazing #dangerous #new",
    "Had the chance to check out this crazy new car by @mercedesbenz 🤯#auto",
    "🤙🫡 #viral #trend #fy #fyp #fypシ #foryou #foryourpage #trend #trending",
    "Car Bollard Barrier Crush - BeamNG.Drive #BeamNG.Drive #carsvsmpilation #crashtestdummies #kultra #monsterjam #rx #springboard #etk #gavril #hirochi #deliveryservice #dsmash #beamngdrive #hulk",
    "Well… we didn‘t checked that #funnyvideos #car #boyfriend",
    "Best movie 😩 #cars #mcqueen #foryoupage #foryou #fyp #fy",
    "#car",
    "Repairing the damage I caused on the Ferrari roof 😬 #ferrari #fyp #foryou",
    "#teagcher #cars #truck #mack #fyp #meme #funny",
    "His & Hers #revvedup #urus #gwagon #garage #couples #cartok #fyp #lambo",
    "#car #auto #vehicle #carro #automobile #automotive #Xsilence",
    "#carro #vehicle #auto #car",
    "Como pensaba que sería la universidad vs Como es realmente la universidad! Insta: car.delorenzo",
    "💥 Superheros but Car ⚡| All superheros car 🔥#superhero #car #marvel #shorts",
    "𝐌𝐞𝐫𝐜𝐞𝐝𝐞𝐬-𝐁𝐞𝐧𝐳 𝐀𝐌𝐆 𝐎𝐍𝐄 #mine_cars #mercedes sbenz #mercedes #amgone",
    "Porsche Brabus 🖤. #sportscar #luxury #luxurycars #xyzbca #fp #foryou",
    "#toys #car #tiktok #fyp",
    "Cars#cartok #top10scary #cartoon",
    "Guess the car 😁🤔 | 🎥@THE-LOWDOWN.com | #4k #quality",
    "The Bugatti that was never made...👀🔥#bugatti #conceptcars #supercar",
    "Cars Jump Competition In Reverse 😂😂😂 #beamng #beamngdrive #car #fyp",
    "You cannot beat this car in a fair fight. #cars #car #carlife #carspotting",
    "𝐏𝐞𝐫𝐟𝐞𝐜𝐭 𝐅𝐨𝐫 𝐃𝐫𝐢𝐟𝐭❤️‍🔥 • 🎥:𝐃𝐫𝐢𝐟𝐭𝐌𝐚𝐬𝐭𝐞𝐫𝐬 • #jdm #drift #car #edit #teamnaraedt",
    "𝐑𝐨𝐧𝐜𝐨 𝐝𝐞𝐬𝐭𝐞 𝐌𝐮𝐬𝐭𝐚𝐧𝐠 😩🔥 | 🎥 - AI edts #carsoftiktok #mustang #fyp",
    "BMW LOVERS 🔥😈 #CapCut #foryou #cars #videoviral #carslover #CapCut",
    "gmfu 😩💚 • 🎥 Remnantmedia #nissan #gtr #r35 #caredit #edit #trending #viral",
    "wow 😲😲😳😳#tatlongbilyon #tiktoktoy #halloween2023 #toycars",
    "#m #car #toys #😂 #fyb #toyscar #ReadySe #GetCrackin",
    "This song 😩🎵 | 🎥@dated. | #4k #quality #car #edit #teamfx⚜️ #swxft",
    "Small to Big cars. ¡Uno más! #toys #juguetes #viral #small #big",
    "wow#car #BMW #carsoftiktok #christmas",
    "Check out the Ferrari F8 Tributo! 😱🔥#ferrari #sportcar #cars",
    "Cars Colors #vídeoskids #videountukanak #للأطفال #game",
    "Best Looking M4 on TikTok? @M4 Dave #bmw #bmwm4 #germancars #g82",
    "#foryoupage #car #skill #drivingskills",
    "Satisfying with Miniature Van model car #mohinhxe #diecast #modelcar",
    "#cleantok #car #satisfying",
    "THE CAR WOULDN’T RESTART",
    "Fast and Furious 🇺🇸😁 - #fyp #foryou #foryoupage #car #cars #auto #carpron",
    "😶‍🌫️🎥 #fypシ゚ #fyp #tiktoksouthafrica #viral #trending #cars #SAMA28",
    "gtr gal #carsoftiktok #gtr #nissangtr #cargirl",
    "Black Supra ❤️‍🔥🛐 | 🎥 HYCADE | #toyota #supra #jdm #car #edit #trending #fyp",
    "Washing a #bmw super dirty mud #dirtycar #bmwmotorsport",
    "crushing soft and crunchy things by car experiment #mostsatisfyingvideo",
    "Toujours un choix compliqué 😬 #car #delorean #dmc #cars #auto",
    "INSTANT KARMA#TROLLFACE #karma #car",
    "🤘🔥#silvias #jdm #car",
    "#car #babycar #mom #kids #toy #foryou",
    "Marry me? 💍 #car #cartok #carsoftiktok #vw #vwgolf #ring #fyp",
    "Lightning McQueen Spider Eater - Coffin Dance Song (COVER)",
    "#britishhumour #britishbanter #britishmemes #imjustbait #gcsememes",
    "racingcar #racingcar",
    "Funzt wah 😂😂😂#wasser #dtm #carporn #digital132 #speed #viral",
    "This view + clean car setup 🤭 #cartok #dreamcar #luxurycars #fypシ゚viral",
    "#toycar #toy #vehicle #DanceWithTurboTax #GetCrackin",
    "Whatever You Land On, 1V1 Skill!! 🙈😱 #foryoupage #foryou #fyp #pov",
    "#CapCut car driving #foryoupage #viralvideo #newtrend #cartiktok",
    "Bounce Mode is a whole vibe 🤣🙌🏻 #cars #car #fyp #tomiconic",
    "MERCEDES BLACK COLOUR 🖤🔥 #videoviral #marcedes #carslover",
    "antistress #car #jdm #challanger #japan #dodge #demon #toyota #supra #mk4",
    "Learn how to drive a car away in just one minute!#tiktok#howto#cartok#car#automotive",
    "2024 Porsche Taycan pink color🚀🔋🔌 #porsche #xeporsche #porschetaycan",
    "Insane | 🎥@4kluxa | #porsche #911 #gt3 #rs #porsche911gt3rs #992gt3rs",
    "Try to recreate this technique 💗 #carstiktok #mercedesamgf1 #cargirls",
    "🌧️ #ferrari #f1weekend #carsoftiktok",
    "#CapCut #stancenation #camber #cambergang #supra #gtr #stance",
    "It’s a HEELy good idea you guys 👀😂 #carhacks #cartok #hacks",
    "toys gadi Khilona🤷🤷🤷🤷🤷🤷🤷🤷🍎😊😊🤣🤣😊😊🔥🔥🥰❤️😍👑😜😜🤔🧐🙈🔥🔥🤩🤩🤩🤩🤩",
    "When your wife doesn’t plug the Tesla in 😫 #teslaowners #teslacharging",
    "It can definitley wink at other cars🤣 #bmw #gina #conceptcar #foryoupage",
    "Disney car mcqueen #cartoys #carforkids #kidscar #disneycars",
    "This bug😍#fyp #bugatti #chiron #hypercar",
    "Super long vid of car Washing #vw #asmr #satisfying #carwash #fyp",
    "sorry not sorry 😉 @avahmejia #cartiktok #cargirlfriend #carcouple",
    "The LaFerrari brings music to our ears 🎵 • #laferrari #ferrari #asmr #joemacari",
    "#speedmodelcar #top #highspeed",
    "Storm 210mph🥶🔥#cars #fyp #ibrahim #carsfan #cartok #lightingmcqueen",
    "Come and learn how to drive a manual transmission car!#tiktok #howto #cartok",
    "| Never noticed as a kid | Cars | Jokes | #ligthningmcqueen #cars #foryou",
    "#car #miata #fyp",
    "Qui veut jouer ? #car #cars #auto #automobile #fy #fyp",
    "18s ftw #stance #lexus #bippujapanstyle #bippu #camber #fitment",
    "Car Safety Ramps 😲 cool gadgets #gadget #ramp #car #carramp #hacks",
    "You can literally land a helicopter on the world's longest car! 🤯🚁 #limo",
    "We’ve just uploaded the Lightning McQueen Virtual Tour 🏎️🔥. Visit Autoviewpoint.co.uk to explore this car in 3D 🎮",
    "what even is that?? #satisfy #satifying #cars #car #window #tint #joke #funnyy",
    "CAR LOVERS 🔥😎 #cars #shorts #carsstory #foryou #viralvideo #cars",
    "This ford fiesta sounded great tbf 😮‍💨 #bonnielocket #cartok #fyp #cars",
    "🎥@FRZMusicz #caredit #supramk4 #CapCut #Edit #4k #carsedit4k",
    "This $2M Mansory Lamborghini Urus is pure luxury on wheels! 🤩👑Thanks to Mansory for this exclusive look! 🤝",
    "Could you get out of this space ? #fyp #viral #share #brilliant #amazing #😂",
    "Wow that waa loud 😮‍💨 #cars #cartok #fyp #viral",
    "Stock my new car with me…😍🤌🏼 #asmr #newcar #restock #denali #gmc",
    "Mehran Gaddi #foryou #fyp #foryoupage #mehran #mehrangadi",
    "#2023 #now #maclaren #car #viralvideo #foryoupage #sportscar304",
    "break X wow = more break #cartok #car",
    "Spraying a car in the BLACKEST PAINT in the UNIVERSE! Black 4.0 says it's darker and blacker than Vanta Black and Musuo Black. Sprayed over a peelable Plasti Dip base so we can reverse back to original with no harm. FULL VIDEO on DipYourCar YouTube",
    "Night of Drift… 😮‍💨🔥| #car #edit #drift #jdm #driftmasters #carsoftiktok",
    "#automobile #Carro #car #vehicle #auto #electriccar #electricvehicle #Xsilence",
    "𝗢𝗹𝗱 𝘁𝗿𝗲𝗻𝗱 ✨ | 🎥 The YARD Club | #mclaren #765lt #mclaren765lt",
    "This is a simple guide to the most essential car parts. #greenscreen",
    "This takes INSANE SKILL. 🤯🔥 (via @ᴋᴡᴛ ) #race #racing #drift #drifting #f1",
    "𝐅𝐞𝐫𝐫𝐚𝐫𝐢 𝐋𝐚𝐅𝐞𝐫𝐫𝐚𝐢 𝐀𝐩𝐞𝐫𝐭𝐚 | 𝟏 𝐨𝐟 𝟐𝟏𝟎 #ferrari #laferrari inghorse #ferrari #caredits",
    "Who needs the pads? #fyp #carlife #carthing #quiet #car",
    "Madness #fyp #fypシ #tiktok #foryou #carsoftiktok #foryoupage #viral #audi",
    "Toyota Century SUV: Where luxury meets state-of-the-art technology! 🚗🔥",
    "This is the glass floor car from the future 🤯🔥#supercarblondie #concept",
    "#tiktok #fyp #cars",
    "Are Priuses cool now? #cars #toyota #foryou #foryoupage #fypシ",
    "Someone’s getting into the Christmas spirit 🎄 #gran #dance #fyp #ouma #car",
    "#toycarforkid #2t_kidtoy #kidtoy #toy #car",
    "A 3 is crazy #cars #fyp",
    "Nissan GTR R35 Liberty Walk V.2 #cars #fyp #nissan #gtr #r35 #supercar #jdm",
    "Bus car toy video #forkids",
    "Give them a roar!! Rev all of your cars!! THROWBACK to our first viral video ❤️",
    "#ASMR Ferrari SF90 Stradale #mastercarsreview #fyp #lebanon #cars",
    "Mcqueen ❤️ #carsoftiktok #cars #cartiktok #rx7",
    "Cane’s sauce is just too good not to take a sip of 😩😍🔥 first Cane’s car mukbang 😋🥰",
    "Let it rain🌧 #car #storm #cars #dodge #charger #rain",
    "painting the scratches on my car with okay results",
    "Car vs Spikes #subaru #wrx #car #spikes",
    "LIGHTS OFF 🌃 #warofdefeat #car #speed #tunned #race #ferrari",
    "Let's practice manual car start together!#driving #drive #car #carsoft #tips",
    "Because I know you enjoy these for some reason 😅🔥 #cars #car #fyp",
    "Satisfying snow foam! 😍 #valeting #snowfoam #satisfying #detailing #fyp",
    "Audi The King 👑 #audi #audir8 #audir8v10 #sports #cars #carsoftiktok",
    "Lamborghini #viral #car #lamborghini #utvjapan",
    "Turn right to go left… #fyp #foryou #foryoupage #viral #memes",
    "#funnyvideos #carsoftiktok #theboys",
    "#drift #drifting #driftcar #fyp #foryou #driftcars #driftking #supra #mustang",
    "Baby Driver #babydriver #movie #car #fyp",
    "$11300 Ferrari restoration part1 #ferrari #carrestoration #restoration #fyp",
    "These little knowledge, automotive engineers do not necessarily know!",
    "Guido cold asf 🥶 #cars #guido #edit #lightningmcqueen #disney",
    "Only 5% of People Know These 10 Secret Car Features!#car #driving #tips",
    "Mercedes-Benz SL 63 AMG Cabrio #mercedesbenz #sl63 #amg #sportcars",
    "Can you relate? 😅 #car #cars #fyp",
    "#car so cool",
    "What would you say is the worst car to drive 😉? #car #lamborghini #ferrari",
    "super car #supercarblondie #taimoorcheema66 #foryoupage #fypシ",
    "toy car | car toys #reels #thefamilyenterprise #viral #foryoupage",
    "#xbox airout 👀📸 #fortheboys #fyp #foryoupage #citigolf #bagged",
    "#CapCut Sport car #fyp #carlife #awesome #car",
    "Im a Driver II #babydriver #babydriveredit #car #drift #drifting #film #filmedit",
    "LOVE IT!!! 😍 #cleaningtiktok #cleaning",
    "Just had to TikTok this girl fucking up my car yesterday 😂😂",
    "So Hot 😩🛐❤️‍🔥-📸@theprovideo.inc #fyp #foryou #viral #trend #edit #edits",
    "Pagani Huayra Coupe in Exposed Carbon | 1 of 1 🔥 #carsoftiktok #viralvideo #fyp",
    "#car #rec #whelsonthebus #babydoll😍 #driver #mycar",
    "POV... Getting ripped off on a car you just bought online 😭😭😭 #stealership",
    "Lamborghini Aventador S 🖤🥷🏼 | #lamborghini #aventador",
    "The 3 coolest cars I've ever seen! 🔥😍 #coolcars #cooltech #conceptcar",
    "How To Open Car Without Keys❗️WoooooW i cannot believe it’s working on my car",
    "Day in the life of a detailer disaster detail edition #cardetailing #detailer #carwash",
    "#vfx #car #funny where are you going? Bro",
    "𝐁𝐌𝐖 🔥 | 🎥 - Ae Motion #teamfx⚜️ #jdm #cars #bmw #bmwm4 #quality",
    "New TOYOTA Hilux Test Drive !#اكسبلور #dzpower #dz #algerie #algeria #car",
    "I mean why wouldn’t you! #carmodifying #carmodification #carmod #starlight",
    "Replying to @k.vroomvroom his secret in Disney cars is confusing everyone!!",
    "bmw💪☠️ #bmw #bmwmotorsport #bmwlove #editing #cars_editz65 #edit",
    "soggy car it is",
    "The life of a driving instructor 😂🚗 🎥: @drivingschooltv #cars #funny #travel",
    "Whats the worst car someone can drive? 😅",
    "The Ferrari Purosangue 715hp 6.5L V12 🏁 First ever four door, four seater car in Ferrari’s history $398,350 MSRP 715hp 6.5L Naturally Aspirated V12 with a redline of 8250rpm 0-62 mph in just 3.2 seconds “0-100 km/h” Top Speed of 193 mph “>310 km/h Dual Clutch 8-speed F1 DCT",
    "The $8 million car!! 😱 #supercarblondie #bugattidivo #bugatti #luxury",
    "Spitting flames 🔥 #cartok #fyp #viral #cars",
    "Porsche 911 means 911 hours of editing 😂 #carphotography #carvideography",
    "#cars #carsoftiktok #cartok #fypシ #detailing #YOUAREAWESOME #viral",
    "Les voitures gelées par le froid 🥶 #adok #automobile #froid #carasmr",
    "P1 😩#mclaren #carspotting #supercars",
    "Flying cars are here!! 😍 #flyingcar #future #techtok",
    "Would You Rather? SUPERCARS EDITION #1 #cars #carsoftiktok #supercar",
    "Children's remote-controlled electric vehicle#toy #toycar #children",
    "#subaru #wrx #sti #v7 #carasmr #cartiktok",
    "kangaroo in car ride #trend #CapCut #kangaroo",
    "You did good, Cars... you did good 👌🔥#fyp #foryou #cars #pixar #tuners",
    "Car vibes 🕺🏾",
    "When parking your car in london…. #l#lamborghini l#lambo l#lamborghiniurus u",
    "𝐜𝐚𝐫 𝐫𝐞𝐯𝐞𝐚𝐥 🤭 • #bugatti #supercar #cars #edit #viral #trending #parati #fyp",
    "#f1 #formula1 #safetycar #indycar",
    "Should I add something?😍 #car #pinkcar #cardecoration #cardecor",
    "Which is your favorite?",
    "Wash my 1:18 Dodge Challenger SRT Hellcat Redeye 🙌🏼🧼 #srt #hellcat",
    "5,500lbs of thrust 🔥 #jetcar #jetfunnycar #prattandwhitney",
    "#softcar #homecar #vlog #travel #camping #carvideos",
    "Who likes car washing?! #fyp #carwash #satisfying #asmrsounds #spray",
    "Do you want one?#auto #car #cars #cartiktok",
    "Im cook 🧑🏻‍🍳 #caredit #edit #cars #carvideography",
    "#goodthing #cargoodthing #car #cars",
    "be aggressive b e aggressive #yellow #car #yellowcar",
    "Another #amazing #reveal here of 2015 Sauber #f1 #car awaiting its conversion by Tour De Force check them out.. 🙌👊😎",
    "#asmrwashing #washingasmr #truckwash #asmrcleaning #washingcar",
    "Faster than a 10 speed🥱 #corvette #fyp #carcommunity",
    "Flaming R35 Liberty Walk V.2 On The Road🔥|🎥:Woyshnis Media#wallpaper",
    "#car #specialeffects #trending",
    "Fully sent it 😮‍💨 #fyp #bonnielocket #cartok #cars",
    "Always eyes on the road - they say :) #crash #accident #funnyvideos",
    "Can I one-up @whistlindieselvstiktok2 ?! Comment below - and make sure to check out his new video on YouTube!",
    "#fyp #ferrari #cars",
    "Buying a car from carvana #fyp #newcar #carvana #vendingmachine",
    "Part 2 Audi A5 Coupe starlights #starlight #fibre #optic #carmods #car",
    "#detailing #cardetailing #detailingproducts #carwashing",
    "#carasmr #mercedes #gle53 #amg #GLE",
    "4k Quality | 🔥 𝐒𝐮𝐩𝐫𝐚 𝐌𝐊𝟒 | 🎥- 𝐏𝐫𝐨 𝐯𝐢𝐝𝐞𝐨 𝐀𝐞 #4k #quality #car #edit",
    "Cheese #fyp #cheese #viral",
    "#CapCut #fyp #cars",
    "#CapCut Car template🔥#mobil #bmw #speedramp #caredit #fyp #viral 📹||",
    "⚡️ #rayomcqueen #jacksomstorm #radiadorsprings #cars #disney #pixar",
    "#drift #driftcar #drifting #driftcars #fyp #foryou #foryoupage #driftking",
    "No way! #cars #wmom #trending #carspot #fypシ #viral #gt3philipp",
    "Tag someone who needs to learn how to parallel park 😅 ##fyp ##worldrecord @",
    "Get yours now! #carinterior #carcommunity #allcantara",
    "This is definitely the most complete wrapping process on tiktok ,it’s not that hard,try yourself!!",
    "Typical Mustang Stuff… #foryou #foryoupage #trending #mclaren #cars",
    "Engine sounds",
    "girl with Bugatti 🔥🤤🩷 #buggati #carros #fy #carhub",
    "My car got stolen",
    "Cars Is So good : cc: @woodl | #cars #carsedit #lightningmcqueen #pixar",
    "Not me walking so confidently up to it as well 🫠😂😳 #rollsroyce #dubaicars",
    "Prime McQueen 😳 | Credits @timikz_ #mcqueen #cars #pixar #storm #95mcl",
    "Celebrating 100k on Insta reposting most viral vid! Thank you 🙏🏽 #bimmer",
    "Répondre à @Roberto partie 2 en commentaire ➡️ #carly #diag",
    "First car accident documented 🥲 #caraccident #caughtoncamera",
    "Gear shifts",
    "This Capcut template slaps on the M4 ngl 🦇 #g82 #g82m4 #m4 #cars",
    "Camaro ZL1 in the sunset 🌅🖤 #camarozl1 #sunset #chevrolet",
    "#carmemes #carscene #carcommunity #electriccars #tesla #carmods Credit to Caaddicts",
    "Volume up 🔊 You're welcome…   #GordonMurray #GMA #T50 #V12 #F1",
    "#cars #car #fyp #fy #viral",
    "Reply to @finnegan_clam Now he is my BOSS 😥#carwash #cleaning #cleancar",
    "Another car detail! #car #cars #foryou #fypシ #fypシ゚viral",
    "#cars #fyp #porsche #viral #foryou #carsoftiktok #viralvideo #beautiful",
    "🔥🔥 #editsbybishnu #jdm #cars #fy #viral #foryou #caredit",
    "Sneaky urus #fyp #lamborghini #concept #urus #aventador",
    "Was ist eurer Traumauto?#CapCutVelocity #CarTuning",
    "Silly cars #silly #sillycars #cats #cars #sillycats #cat #cattiktok #foryou #viral",
    "𝐌𝐚𝐟𝐢𝐚 𝐕𝐢𝐛𝐞𝐬😶‍🌫️🛐||LIMMA|| #car #cars #edits #edit #BMW #X6M #fypシ #Fyp",
    "“You brought me a mustang…” 😭(Credits T&T Creative Media and Amy Green)",
    "Disney Cars games evolution #lightningmcqueen #disney #cars",
    "Nearly Dented The 488 😭 #car #cars #carspotting #carsoftiktok #fyp",
    "wait for it 👀 . . . #cars #carslover #fy #fypシ #fyy #fyyyyyyyyyyyyyyyy",
    "This Duo Drift😩💞|🎥@kenfilms #drift #drifting #jdm #jdmcars #car #carros",
    "This garage is absolute goals 🤩 #TheTripleFCollection #Ferrari #McLaren",
    "STEALTH PPF for the Taycan Sport turismo 🤩 #car #wrap #carwrapping",
    "Be honest, you buying an Apple Car??? 🤔 #matthadouken #apple #applecar",
    "#cars #foryou #fypcar #fypシ゚viral #foryoupagе #95",
    "Carsleepover🥰",
    "Honda E #carsoftiktok #holdcroft #holdcroftgroup #cardealership",
    "To make Nick's car cooler than O'Neal's, Nick decided to heavily modify the car",
    "The Audi AI:CON is so futuristic they put it in the Museum of the Future! 🔥👀 #audi",
    "This is the definition of the luxury 😍 #supercarblondie #hautevoiture",
    "Cars 1 solos. #mcqueen #cars #pixar #lightningmcqueen #95mcl",
    "What courtesy cars have you had 🤷‍♂️ #carcleaning #storytime #satisfying",
    "My Summer Car Online Intrusive Thoughts Won #msco #mysummercar #msc",
    "I have to try it in the car #Invertido",
    "2013 #audi #s7 v8 #carasmr #sonnyG",
    "Carly Dancing Again 😂😳😂",
    "Dodge 😈🔥 #foryou #dodge #challenger #car #edit #fyp #abir_editzz",
    "$5 a gallon with 8 MPG😌 • • • #funnyvideos #fypシ #corvette #foryou",
    "Baby cars🚗 #cars #carsoftiktok #carslover #carspotting #car #porsche",
    "Replying to @cheenaloverbhakkar New trend in pakistan of this week #CapCut",
    "car season start 🏎😍🔥 #drift #드리프트 #아주자동차대학교 #driftcar #driftgirl #피치스레이싱",
    "#tiktok #movie #fyp #cars1 #owenwilson #lightningmcqueen95",
    "I'm Lightning ⚡ #cars #lightningmcqueen #pixar @𝕃𝕄𝟟𝔻",
    "#forzahorizon5 #forzahorizon5go #gaming #gamer #cars #fyp #foryou",
    "A beginners guide! Tag someone’s who’s just got a fiat 500👇🏼 #howto #fiat",
    "𝐏𝐨𝐫𝐬𝐜𝐡𝐞 𝟗𝟏𝟏 𝐆𝐓𝟑 𝐑𝐒 | 𝐅𝐑𝐄𝐄 𝐂𝐋𝐈𝐏𝐒 🖤 • #cars #edit #viral #trending #parati",
    "Just taking a walk! 🤭 #mercedesamg #mercedesbenz #carsoftiktok #cartok",
    "Squad is back 🤪 #cars #carguy #cargirl #carmeet",
    "BMW Like A 😈 🥵🩶 #foryoupage #foryou #carlover #ak_cars",
    "RIP My hero😔💔 #chickhicks #lightningmcqueen #cars",
    "Now it’s a racecar! #tesla #car #debagde #racecar #nj #business #ppf #ceramic",
    "Subaru 🤍|🎥@Woyshnis Media #4k #fyp #subaru #edit #car #jdm",
    "Is it that bad?",
    "𝗗𝗿𝗶𝗳𝘁 𝗠𝗮𝘀𝘁𝗲𝗿𝘀 𝟮𝟬𝟮𝟭 🎥 Scott Mitchell #fyp #edit #foryou #car #jdm #jdmcars",
    "This one is crazy😳 #carplay",
    "Color of money. #carexpert",
    "There is a reptile-like appearance to this car🤯 #bmw #vision #conceptcars",
    "#tiktok #movie #fyp #cars3 #owenwilson #lightningmcqueen95",
    "Got to shoot with LIBERTY WALK R35 CRAZY FLAMES ! By @masterjohn_ || IG . . . .",
    "Mustang GT 500 😍 Credits - Fathouse performance (yt) #fyp #cars",
    "mercedes 🤤🔥 #fyp #keşfet #mersedes #mercedesdance #dance #mybach",
    "Made myself a new daily 😎 #car #cars #bmw #cartok #cartok #transformation",
    "The coolest little car you’ve ever seen!",
    "now he's just showing off #bf #gr86 #grandhighlander #carcouple #outoffuel",
    "Hellcat sound 😈🔥#dodge #challenger #dodgechallenger #hellcat",
    "The rule of 4 ! #detailing #cars #carsoftiktok #valet #exterior #interior",
    "Do you want to this?#carlover #car #goodthing #fyp #carcare",
    "Since someone asked:) #cars #masarati",
    "Microlino - How to get inside #Microlino #Micro #autoappassionati",
    "Car ferry #amazeforce #smart #learnontiktok #foryoupage #foryou",
    "Only hot bois around here #cartok #cartiktok #carcommunity #supra",
    "#cars #cars2 #fyp #allinol #geneva #switzerland",
    "Just #MR2 things I guess 🤷‍♂️ #flooded #jdm #fyp",
    "These cars are literally ALIVE! 🤯🔥 #transformers #audi #future",
    "Wait for it 🔥🤤 🎥 Bobolov Productions & FLICKY MEDIA #fyp #fypシ #fy",
    "You don't have to worry about a puncture anymy😂😂#car #carlovers #mycars",
    "SET THE GAS #drivinglessons #drivingtips #learntodrive",
    "@DangerRanger @BassFanatic @P Shizzle @Parker Dacchille #caraudio",
    "MIATA:D #foryou #foryoupage #cars #miata🐸 @Helene🏎 @Spicy🌶",
    "Cars vs 2 Giant Hammers #beamngdrive",
    "This Is The World's Fastest Car! The Speed Is 763MPH or 1227KM/H 😱",
    "ASMR of Bugatti Chiron Pur Sport | 1 of 60💙 #fyp #foryoupage #goviral",
    "#campinglife #travelling #campinginrain #holiday #outdoors #carcamping",
    "Enjoy this minute long video of Gotham 992🦇 📸:@luca #cars #carsoftiktok",
    "part two of creating a decorative lining for the inside of my mollie! so far so good…. 🫣",
    "🤦🏻‍♀️ #carguy #carboyfriend #carcouple #fyp #carscene #carmeets #carlife",
    "Very much needed it #carcleaning #satisfying #asmr #fyp #foryou",
    "Watch me take 'fake it till you make it' to a whole new level as I cruise the streets of London in my imaginary Buggati 😎🚙",
    "JDM 🇯🇵🔥#photography #tokyo #japan #秋葉原 #関東 #JDM #jdmcars #cars",
    "Audi R8 🏎️ 💨 #audi #audisport #r8 #r8v10 #audimotorsport #rs #supercar",
    "#carmat #carbeauty",
    "redeye😮‍💨🔥#hellcat #cars #redeye #dodge #hellcaredeye #carsphk #viral",
    "Game Vs. Movie, Cars The Movie, Lightning Mcqueen tries to escape Radiator Springs after destroying it!",
    "It’s a mom car 😂 #carsoftiktok #cars #fyp",
    "ASMR BMW Seria 7 🥰 #bmwbestautolublin #bmwseria7",
    "Ya officer let me just grab my booster seat #240sx #s14 #driftcar",
    "shmees zenvo #cloudycars #cloudycreps #shmee #shmee150",
    "Just saying 🤣 #fypシ #foryoupage #hellcat #cars #race #scatpack",
    "R34🥵|🎥@hycade |#car #caredit #cartok #capcut #toyota #supra #mk4",
    "Cars 2|| Película completa|| #entretenimiento #Cars #Viral #filmclips",
    "LB-SILHOUETTE GTR R35|🎥:dated.#wallpaper #gtr #gtrr35 #r35 #lbwk",
    "🎥Hoonigan • No Legged Drift Legend#cars #japan90sdrift #hoonigan #caredits",
    "OSCARS WEEKEND!! One of my fav oscars Glambots of all time with Cara Delevigne!",
    "Replying to @Josie anyone else in the pink jetta club?🥹💕 #kikialchemymobile",
    "#wrcgenerations #wrc #rally #cars #steeringwheel #fyp #games",
    "base model charger activites 💀 #carspotting #cars #carsoftiktok",
    "the transition 😭 #dad #cars #carsurprise #emotional #sad #cartok",
    "Beating you up for no reason #relatable #yellowcar #foryou #fyp #uk",
    "fastest cars on earth // #fyp #f1 #formula1 #viral #speed",
    "this car is ...🥵#dodge #edit #cars #alightmotion",
    "Have you ever seen a car with its own built-in camera washing robots? 😂",
    "𝐁𝐞𝐬𝐭 𝐜𝐚𝐫𝐬 😈🤤 | 🎥 - Tubepower • #carros #🥵 #toyota #mercedes #parati",
    "With its crazy cyberpunk interior, Nissan's brand new Hyper Force is the sports car of the future 😍🔥",
    "Second date car✌🏽#car #cars #carscene #quebec #toyota #mr2 #oldschool",
    "Deeply cleaning #fyp #carwash #cleaninghack #satisfying",
    "Épisode 3 |✨Martin race drift✨#martin #cars #car #cars1 #cars2 #cars3 #speed",
    "SUV Driver “oh didn’t see you there ,How dare you Scratch my tires with your little plastic Lunchbox !!?” , TRUCKs & SUVs run these streets !",
    "Imagine Not Showing Up In A Heli 😂#prom #miura #helicopter #bhoycars",
    "Would you Laugh or Cry ? 🤣😭 Comment down below 🙈🙈 Go follow our instagram account",
    "Replying to @teq The fastest 6 wheel car of all time only mercedes can make cars like these",
    "Be honest is she still goofey? 🤭.. guess the next car modification 🫵🏼 #carmod",
    "only in dubai🤩 #fyp #foryou #cars #dxb #dubai #rich",
    "Respuesta a @never_dies.4 #sigueme #paratiiiiii #cars2 #cars",
    "The best car of the show was driven by a woman 🫠(I loved that it was a woman instead if a guy so please read it or don’t comment)",
    "What if #carsfan99 #cars #carsfan #edit #pixar #fyp #disney #CarsTikTok",
    "Torque tem ronco? Porque se tiver... é esse barulho aí! 🤣 Supercharger do Hellcat alimentando os 807hp do V8tão! Insano! 🚗 Dodge Challenger Hellcat Jailbreak .",
    "She’s pretty💗 #fyp #foryoupage #trending #viral #foryoupageofficiall",
    "Stance Is Not A? #taburthecarguy #golf #bagged #stance #volkswagen #vw",
    "Car picnic 🚙🍕 #carpicnic #carpicnicdate #datenight #foryou",
    "Five quirky things we love about the Citroën Ami. 🙌🏼 #citroenami #citroenuk",
    "What a beast 😈 #brtcars #cars #car #koenigsegg #rarecars #trending",
    "#twinsies",
    "New car essentials part 1 🥰 #CapCut #newcar #blackonblacknightshade",
    "🙉 #greenscreenvideo #hotpit #bmw #jdm #s13 #carsoftiktok #hotpit #drift",
    "#parati #clasic #rines #ayudame #tuningcars #turbo #fyp #drif #carshow",
    "CGI is taking over the new Kia car! Credits: @nps3d #njedit #njeditcanada",
]
